#!/bin/bash

# ==============================================================================
# Linux TCP/IP & BBR - Balanced Performance Optimization Script
#
# Description: This script enables TCP BBR and applies a balanced set of sysctl
#              optimizations suitable for a wide range of modern servers.
#              It aims for significant performance gains without being overly
#              aggressive on resource consumption, making it ideal for typical
#              cloud servers (e.g., 2-4 cores, 4-8GB RAM).
# ==============================================================================

set -e # Exit immediately if a command exits with a non-zero status.

# --- Configuration ---
# 配置文件路径已根据您的要求指定
CONF_FILE="/etc/sysctl.d/99-bbr.conf"

# --- Pre-flight Checks ---

# 1. Check for root privileges
if [[ $(id -u) -ne 0 ]]; then
    echo "❌ 错误: 此脚本必须以 root 权限运行。"
    echo "请尝试使用: sudo $0"
    exit 1
fi

# 2. Check for Kernel version (BBR requires 4.9+)
KERNEL_VERSION=$(uname -r)
KERNEL_MAJOR=$(echo "$KERNEL_VERSION" | cut -d. -f1)
KERNEL_MINOR=$(echo "$KERNEL_VERSION" | cut -d. -f2)

if (( KERNEL_MAJOR < 4 )) || (( KERNEL_MAJOR == 4 && KERNEL_MINOR < 9 )); then
    echo "❌ 错误: 检测到内核版本为 $KERNEL_VERSION。"
    echo "BBR 拥塞控制算法需要 Linux 内核版本 4.9 或更高。"
    exit 1
else
    echo "✅ 内核版本 $KERNEL_VERSION 符合要求。"
fi

# --- Main Logic ---

# Function to add a sysctl key-value pair
add_conf() {
    local key="$1"
    local value="$2"
    echo "$key = $value" >> "$CONF_FILE"
    echo "[新增] $key = $value"
}

# --- Backup and Configuration ---

echo "--------------------------------------------------"
echo ">>> 准备写入网络优化配置到 $CONF_FILE ..."

# Create a timestamped backup if the configuration file already exists
if [ -f "$CONF_FILE" ]; then
    BAK_FILE="$CONF_FILE.bak_$(date +%F_%H-%M-%S)"
    echo "发现已存在的配置文件，正在创建备份: $BAK_FILE"
    cp "$CONF_FILE" "$BAK_FILE"
fi
# Initialize the file for a clean write
> "$CONF_FILE"
echo "# Generated by balanced network optimization script on $(date)" >> "$CONF_FILE"
echo "# This configuration provides a balance between performance and resource usage." >> "$CONF_FILE"
echo "" >> "$CONF_FILE"


echo ">>> 写入优化参数..."

# --- BBR 启用 ---
add_conf "net.core.default_qdisc" "fq"
add_conf "net.ipv4.tcp_congestion_control" "bbr"

# --- 内存和缓冲区优化 ---
add_conf "net.core.rmem_max" "33554432"
add_conf "net.core.wmem_max" "33554432"
add_conf "net.ipv4.tcp_rmem" "4096 87380 33554432"
add_conf "net.ipv4.tcp_wmem" "4096 65536 33554432"

# --- 连接队列优化 ---
add_conf "net.core.somaxconn" "65535"
add_conf "net.core.netdev_max_backlog" "65535"
add_conf "net.ipv4.tcp_max_syn_backlog" "16384"

# --- TCP 行为优化 ---
add_conf "net.ipv4.tcp_mtu_probing" "1"
add_conf "net.ipv4.tcp_fastopen" "3"
add_conf "net.ipv4.tcp_fin_timeout" "20"
add_conf "net.ipv4.tcp_synack_retries" "2"
add_conf "net.ipv4.tcp_syn_retries" "2"
add_conf "net.ipv4.tcp_keepalive_time" "600"
add_conf "net.ipv4.tcp_keepalive_intvl" "30"
add_conf "net.ipv4.tcp_keepalive_probes" "5"

# --- TIME_WAIT 状态优化 ---
add_conf "net.ipv4.tcp_tw_reuse" "1"

# --- 其他系统级优化 ---
add_conf "net.ipv4.ip_local_port_range" "1024 65535"
add_conf "fs.file-max" "1048576"
add_conf "net.netfilter.nf_conntrack_max" "524288"

echo "--------------------------------------------------"
echo ">>> 应用 sysctl 配置..."
sysctl --system >/dev/null 2>&1
echo "✅ 配置已应用。"

echo "--------------------------------------------------"
echo ">>> 检查关键优化结果："
echo -n "TCP 拥塞控制算法: "
sysctl -n net.ipv4.tcp_congestion_control
echo -n "默认队列调度算法: "
sysctl -n net.core.default_qdisc
echo -n "最大Socket读/写缓冲区: "
sysctl -n net.core.rmem_max
echo -n "系统文件句柄上限: "
sysctl -n fs.file-max

echo "--------------------------------------------------"
echo ">>> 检查 BBR 模块是否成功启用："
if sysctl net.ipv4.tcp_congestion_control | grep -q "bbr"; then
    if lsmod | grep -q tcp_bbr; then
        echo "✅ BBR 已作为内核模块加载并成功启用。"
    else
        echo "✅ BBR 已内建于内核并成功启用。"
    fi
else
    echo "❌ BBR 未启用。请检查您的内核配置。"
fi

echo "--------------------------------------------------"
echo "🎉 TCP/IP & BBR 优化完成！"
